version: appveyor-preflight-{build}-{branch}
branches:
  only:
  - master
image: Visual Studio 2017
init:
- ps: >-
    git config --global core.autocrlf input

    git config --global credential.helper store
install:
- ps: >-
    Install-Product node 8 x64

    $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version

    Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"
build_script:
- cmd: >-
    npm install

    npm run dist
test: off
artifacts:
- path: dist\*.*
  name: dist
  type: WebDeployPackage
deploy:
- provider: GitHub
  release: v$(package_version)
  auth_token:
    secure: 2pYKQly7IeHYJXLbju2pVzzVbHGE9zPgpDksrdQHeHE4iOF0iq5BXjSVj1hmLfN5
  force_update: true
